Normaliz/Normaliz

.travis-build.sh, .travis.yml
Work in progress to add another Travis CI build that tests the classic Makefile.
=> Add BUILDSYSTEM=classic travis build

.travis-build.sh, .travis.yml, test/Makefile.am
CoCoA on Mac (the Boost problem); add no-openmp build, add cmake-scip builds
=> Updates to Travis scripts

doc/Normaliz.tex
Description: upstream: reproducibility: documentatation
Attempt to remove judiciously the date in the LaTeX source to render
its composition reproducible; see https://reproducible-builds.org/ .
Last-Update: 2018-01-26
=> reproducible documentation

source/libnormaliz/cone.cpp, source/libnormaliz/cone.h
* Made inhom_input a member of Cone
* added resetGrading method
=> Possibility to reset grading:

Dockerfile
to get PyNormaliz to link correctly.
=> Added shared library build to Dockerfile

.travis-build.sh, configure.ac, m4/ax_check_library.m4, source/Makefile.am
=> Refactored flint-checking in configure

source/libnormaliz/cone.cpp
=> Added getter for Float cone property

source/libnormaliz/automorph.cpp, source/libnormaliz/automorph.h
... instead of copying the data
=> Change AutomorphismGroup accessors to return const refs

source/input.cpp, source/libnormaliz/automorph.cpp, source/libnormaliz/cone.cpp, source/libnormaliz/full_cone.cpp, source/libnormaliz/full_cone.h, source/libnormaliz/integer.h, source/libnormaliz/matrix.cpp, source/libnormaliz/matrix.h, source/libnormaliz/normaliz_exception.h, source/libnormaliz/output.cpp
There are a few places in here where this PR changes semantics, and/or where the changes might have uncovered issues; I'll flag them so that they can be reviewed more closely.
=> Fix more compiler warnings, and perhaps some bugs

.travis-build.sh, .travis.yml, bootstrap.sh
This is some cleanup for the Travis setup, trying to untangle some bits in it. Further changes can be built on that later.
=> Tweak Travis setup

download.sh, install_normaliz_with_eantic.sh, install_scripts_opt/install_nmz_arb.sh, install_scripts_opt/install_nmz_cocoa.sh, install_scripts_opt/install_nmz_e-antic.sh, install_scripts_opt/install_nmz_flint.sh, install_scripts_opt/install_nmz_flint_devel.sh, install_scripts_opt/install_nmz_nauty.sh
- now uses curl or wget, depending on which is available
- SHA256 checksum of tarballs is checked
- if a tarball was already downloaded, we don't download it again
=> Add download.sh to make install scripts more robust

source/libnormaliz/nmz_nauty.cpp
Instead use plain std::vector manage the dynamic allocations.
=> Avoid using nauty macros DYNALLSTAT, DYNALLOC2

source/libnormaliz/nmz_polynomial.cpp
Fix indentation, and change a for loop to modern ranged for loop;
note that since G is a reference, we can remove one assignment
to factorsRead[i] in the loop.
The indentation was odd (not to say: broken) because apparently code from different places with completely different formatting styles was mixed. Which makes me wonder: @w-bruns do you have some kind of "preferred formatting style"? Right now, I am just trying to match whatever the surrounding code looks like, but that also is quite inconsistent. I personally prefer try to format code in a somewhat uniform way (but don't care much which way that is, exactly, as long as it doesn't change every 3 lines :-). Perhaps you'd be interested in adding a `.clang-format` file, and then using …
=> Cleanup processInputPolynomial

install_pynormaliz.sh
I'll submit a proper fix to PyNormaliz later, but it requires a little bit more effort.
=> install_pynormaliz.sh: workaround to support custom PREFIX

install_pynormaliz.sh
Also make sure to remove old build artifacts before building
=> Set NORMALIZ_LOCAL_DIR when building PyNormaliz

Makefile.am
=> Makefile.am: add download.sh to EXTRA_DIST

install_normaliz.sh, install_normaliz_with_eantic.sh, install_normaliz_with_opt.sh, install_scripts_opt/common.sh, install_scripts_opt/install_nmz_arb.sh, install_scripts_opt/install_nmz_cocoa.sh, install_scripts_opt/install_nmz_e-antic.sh, install_scripts_opt/install_nmz_e-antic_github.sh, install_scripts_opt/install_nmz_e-antic_vincent.sh, install_scripts_opt/install_nmz_flint.sh, install_scripts_opt/install_nmz_flint_devel.sh, install_scripts_opt/install_nmz_mpfr.sh, install_scripts_opt/install_nmz_nauty.sh
Also move the MPFR installation into its own script to further reduce code duplication
=> Refactor install scripts, put common code into a new file `common.sh`

INSTALL, doc/Normaliz.tex, install_normaliz.sh
=> Remove semistatic build, including NMZ_SHARED, save_dynamic

source/input.cpp, source/libnormaliz/cone.cpp, source/libnormaliz/integer.h, source/libnormaliz/map_operations.h
The resulting code is IMHO clearer, and this name is consistent
with the name of the function for std::set.
=> Rename `exists_element` for std::map to `contains`

.travis-build.sh, .travis.yml, configure.ac, install_normaliz.sh, m4/ax_check_library.m4, source/Makefile.am, test/Makefile.am
This is a work-in-progress alternative to PR #260. It is unfinished, but I wanted to put it here so it's not forgotten. I simply run out of time finishing it, but will hopefully be able to change that soon.
Once finished, this resolves #257 and resolves #233.
=> Refactor configure.ac

.travis-build.sh, Makefile.am, doc/Normaliz.tex, install_normaliz_with_opt.sh, install_scripts_opt/install_eantic_with_prerequisites.sh, install_scripts_opt/install_nmz_flint.sh, install_scripts_opt/install_nmz_flint_devel.sh
Also make sure it is put into the distribution create by `make dist`.
This is extracted from PR #320; I hope it'll pass tests and can then be merged right away, reducing the "moving parts" of PR #320 so I can focus on the rest of it.
=> Call install_nmz_mpfr.sh explicitly

.make-bindist.sh
... by ensuring that only one .tar.gz is put into that repository at a time.
=> Fix macOS bindist

configure.ac
Fixes #342
.... but is completely untested... perhaps @mkoeppe or @saraedum are interested in trying it out.
=> configure.ac: use E-antic CPPFLAGS/LDFLAGS

doc/Normaliz.tex, source/dynamic/dynamic.cpp, source/libnormaliz/collection.cpp, source/libnormaliz/cone.cpp, source/libnormaliz/cone_dual_mode.cpp, source/libnormaliz/cone_property.cpp, source/libnormaliz/full_cone.cpp, source/libnormaliz/full_cone.h, source/libnormaliz/general.cpp, source/libnormaliz/general.h, source/libnormaliz/integer.h, source/libnormaliz/matrix.cpp, source/libnormaliz/matrix.h, source/libnormaliz/nmz_integrate.h, source/libnormaliz/options.h, source/libnormaliz/output.cpp, source/libnormaliz/simplex.cpp, source/maxsimplex/maxsimplex.cpp, source/normaliz.cpp, source/outerpar/outerpar.cpp, test/catch.hpp
=> Avoid `using namespace XYZ` in headers on global level; switch some #includes from C to C++ headers

source/libnormaliz/matrix.h
=> Use std::isnan for compatibility with old GCC

source/Makefile.am, source/libnormaliz/Makefile.classic, source/libnormaliz/options.cpp, source/libnormaliz/options.h
This reduces compile time a bit, and there isn't a point in inlining any of these functions anyway.
=> Move parts of options.h to new options.cpp

configure.ac
... to fix a failure reported in https://trac.sagemath.org/ticket/27952#comment:147
=> configure.ac: Another fix for -larb vs -lflint-arb

.github/workflows/ci.yml
This is *not* the ideal way to set up these things, but rather just a first
step to get our toes wet and figure out what works and what doesn't.
More to follow.
Some things to look into:
- actually make the jobs work
- port over more/all of the Travis jobs
- use a build matrix to reduce duplication among the different jobs (and also to avoid having to pick a "name" for each :-))
- also run Windows tests here
- ... many more things could be done, but one step after the other
=> Some initial GitHub Actions CI tests

source/libnormaliz/automorph.cpp, source/libnormaliz/input_type.h
Reported and fixed by Benjamin Burton.
=> Silence compiler warnings when assertions are off

.github/workflows/ci-sage.yml
Fixes the Cygwin workflow and makes other updates to the tested platforms
=> .github/workflows/ci-sage.yml: Update

source/libnormaliz/face_lattice.cpp, source/libnormaliz/full_cone.cpp, source/libnormaliz/full_cone.h, source/libnormaliz/general.cpp, source/libnormaliz/matrix.cpp, source/libnormaliz/simplex.cpp
code from https://stackoverflow.com/questions/10905892/equivalent-of-gettimeday-for-windows
=> Support MSVC

install_pynormaliz.sh
do not invoke setup.py directly
=> install_pynormaliz.sh: Use 'pip install'
