Normaliz/Normaliz

source/Input.cpp
Issue #26 says gcc 4.4 is supported, but I got the following compilation error about `to_string` with g++ 4.4.7 on Scientific Linux 6.7 (x86_64):
```
[ 88%] Building CXX object CMakeFiles/normaliz.dir/Normaliz.cpp.o
In file included from /user/tueda/tmp/Normaliz/source/Normaliz.cpp:38:
/user/tueda/tmp/Normaliz/source/Input.cpp: In function ‘void read_constraints(std::istream&, long int, std::map<libnormaliz::Type::InputType, std::vector<std::vector<Integer, std::allocator<_Tp1> >, std::allocator<std::vector<Integer, std::allocator<_Tp1> > > >, std::less<libnormaliz::Type::InputType>, std::allocator<std::pair<const libnormaliz::Type::InputType, std::vector<std::vector<Integer, std::allocator<_Tp1> >, std::allocator<std::vector<Integer, std::allocator<_Tp1> > > > > > >&, bool)’: …
```
=> Fix compilation error in gcc 4.4

.travis-build.sh, .travis.yml, configure.ac, source/input.cpp, source/libnormaliz/vector_operations.cpp, source/output.cpp
This branch:
- First checks for C++ 11, then falls back to C++ 0x.
- fixes some of the build failures on Travis CI.
Target `autotools-makedistcheck` didn't set OMP_NUM_THREADS=4, and a result "make check" would hang nondeterministically. Probably normaliz should use better defaults when this environment variable is not set.
- adds Mac OS X build targets (various versions of the OS and of XCode)
Currently these builds fail:
```
/bin/sh ../libtool  --tag=CXX   --mode=link clang++ -std=gnu++11   -g -O2  -L/Users/travis/build/mkoeppe/Normaliz/build_scip_static/scipoptsuite-3.2.1/lib  -o normaliz normaliz.o libnormaliz.la -lscipopt -lgmp -lz -lreadline -lgmpxx -lgmp
/bin/sh ../libtool  --tag=CXX   --mode=link clang++ -std=gnu++11   -g -O2 …
```
=> Improvements to Travis CI build scripts, C++ 11 detection

.travis-build.sh, .travis.yml, Qsource/Makefile.classic, Qsource/Makefile.configuration, Qsource/libQnormaliz/Makefile.classic, source/Makefile.am
This pull request adds more travis tests (in particular some limited tests that what is installed by "make install" works) and catches a typo in the classic Makefile that was exposed by these tests.
By the way, all Travis builds involving "make distcheck" currently fail on branch "towards320" because the repository does not have the following files listed in examples/Makefile.am:
+       rationalES.intOut                       \
+       rationalLC.intOut                       \
+       rationalInt.intOut                      \
=> More travis tests - and a fix for classic Makefile QNormaliz "make install"

.travis.yml, source/INSTALL
(This test currently fails because of some missing CMakeLists.txt)
=> Add Travis tests to ensure that the distribution built by 'make distcheck' includes cmake, classic scripts

source/libnormaliz/cone.cpp
Description: source typo
Correct spelling errors as reported by lintian in the binary library; meant
to silence lintian and eventually to be submitted to the upstream maintainer.
Comment: spelling-error-in-binary
Last-Update: 2017-11-03
=> correct a spelling error as detected by Lintian

test/Makefile.classic
Description: upstream: tests: ignore extremely sensitive tests
Ignore an extremely sensitive test [1] that fails on arm64, ppc64el,
s390x, powerpc and ppc64 architectures at the time of writing.
[1] https://github.com/Normaliz/Normaliz/issues/161
Last-Update: 2017-11-17
=> ignore extremely sensitive test t/t-/5x5PF

source/libnormaliz/matrix.cpp
Add a return clause, because assert() may be replaced with nothing by
the preprocessor under -DNDEBUG.
matrix.cpp: In member function 'std::vector<Integer> libnormaliz::Matrix<Integer>::VxM_div(const
std::vector<Integer>&, const Integer&, bool&) const [with Integer = double]':
matrix.cpp:942:1: warning: no return statement in function returning non-void [-Wreturn-type]
matrix.cpp:2262:1: warning: no return statement in function returning non-void [-Wreturn-type]
matrix.cpp:2696:1: warning: no return statement in function returning non-void [-Wreturn-type]
=> Fix compiler warnings in matrix.cpp

source/INSTALL
=> Xcode clt need to be installed to compile Normaliz

source/libnormaliz/cone.cpp
if no projection coordinates are set. Closes #180.
=> BadInputException for ProjectCone

Qsource/Makefile.am, source/Makefile.am
Description: upstream fix: autotoolization: external build
Allow external build ( mkdir _build; cd _build; ../configure ).
Last-Update: 2018-06-08
=> AutoToolization: allow external build

source/Makefile.am
since general.h (and therefore cone.h) still requests it
I am not really sure if this is the right solution. Do we really want this to be installed, or just all traces of `nmz_config.h` removed?
=> Reinstall nmz_config

source/libnormaliz/full_cone.cpp
Description: source typo
Correct spelling errors as reported by lintian in some binaries;
meant to silence lintian and eventually to be submitted to the
upstream maintainer.
Origin: vendor, debian
Comment: spelling-error-in-binary
Last-Update: 2019-06-07
=> spelling-error-in-binary

source/libnormaliz/cone.h, source/libnormaliz/full_cone.h
With these changes, I can use normaliz again with older C++ compilers.
=> Make cone.h, fullcone.h compatible with older C++ versions

source/libnormaliz/cone_property.h
These macros are taken from GAP, and make maintenance of enum ranges very
easy, thus removing a potential source of mistakes.
=> Introduce START_ENUM_RANGE and END_ENUM_RANGE helper macros

source/libnormaliz/cone.cpp, source/libnormaliz/input_type.cpp, source/libnormaliz/integer.cpp, source/libnormaliz/matrix.cpp, source/libnormaliz/output.cpp, source/libnormaliz/vector_operations.cpp
Bugs:
- Matrix<mpq_class>::VxM was not returning anything
- handling of automorphisms had a misplaces parenthesis
The second fix should be verified, maybe it is not right after all (I'll mark it in a moment).
=> Fix a bunch of compiler warnings, and two actual bugs

source/input.cpp, source/libnormaliz/HilbertSeries.cpp, source/libnormaliz/automorph.cpp, source/libnormaliz/cone.cpp, source/libnormaliz/cone_dual_mode.cpp, source/libnormaliz/full_cone.cpp, source/libnormaliz/integer.cpp, source/libnormaliz/list_operations.cpp, source/libnormaliz/list_operations.h, source/libnormaliz/matrix.cpp, source/libnormaliz/nmz_integral.cpp, source/libnormaliz/nmz_nauty.cpp, source/libnormaliz/nmz_polynomial.cpp, source/libnormaliz/offload_handler.cpp, source/libnormaliz/output.cpp, source/libnormaliz/reduction.cpp, source/libnormaliz/simplex.cpp, source/libnormaliz/vector_operations.cpp, source/libnormaliz/vector_operations.h, source/outerpar/outerpar.cpp
... in most places where it is possible. The resulting code is often
easier to read and maintain. This also enables future refactoring,
e.g. use of ranged for-loops.
Caveat: use of `auto` may not work with OpenMP, but I can't test that locally. So the Travis tests using OpenMP may very well fail, in which case I can update this PR. But before I invest that work, it'd be good to know if there is any interest in this at all, otherwise I'll just drop it.
=> Replace explicit ::iterator with auto keyword

source/input.cpp, source/libnormaliz/HilbertSeries.cpp, source/libnormaliz/automorph.cpp, source/libnormaliz/bottom.cpp, source/libnormaliz/cone.cpp, source/libnormaliz/cone_dual_mode.cpp, source/libnormaliz/descent.cpp, source/libnormaliz/full_cone.cpp, source/libnormaliz/full_cone.h, source/libnormaliz/integer.cpp, source/libnormaliz/list_operations.cpp, source/libnormaliz/list_operations.h, source/libnormaliz/map_operations.h, source/libnormaliz/matrix.cpp, source/libnormaliz/nmz_integral.cpp, source/libnormaliz/nmz_polynomial.cpp, source/libnormaliz/offload_handler.cpp, source/libnormaliz/output.cpp, source/libnormaliz/project_and_lift.cpp, source/libnormaliz/reduction.cpp, source/libnormaliz/simplex.cpp, source/maxsimplex/maxsimplex.cpp, source/options.cpp
This PR changes the code to use C++11 ranged for loops. This makes a lot of the code easier to read (IMHO at least). The first commit was generated using the `clang-tidy` tool, but then a lot of other loops were changed with manual work.
AFAIK, ranged for loops are only supported in OpenMP 5.0, so I'd not be surprised if I broke compilation when using OpenMP; Travis will tell us, and then affected loops can be changed back to "old style".
=> Use ranged for loops from C++11

configure.ac
- require autoconf 2.68, released in 2010; older versions have many bugs
- move AC_CONFIG_FILES to the end, where it usually sits
- replace obsolete AC_PROG_LIBTOOL by LT_INIT
- specify explicit AC_CONFIG_AUX_DIR;  in the future, we could change it from . to cnf
- replace shell comments `#` by m4 comments `dnl` in a few places
This is a very moderate change. The next step will be to replace the various package checks by better ones (which e.g. properly support `--without-FOO`; and which also give an error if `--with-FOO` is explicitly given, but `FOO` does not work / is missing).
As such, this is the start of (= first PR of) an alternative to PR #260.
=> configure.ac: some mild cleanup and refactoring

source/libnormaliz/cone.h, source/libnormaliz/nmz_integral.cpp
This is an internal implementation detail, and should not be exposed to
users of the library.
=> cone.h: don't #include sys/stat.h

doc/Normaliz.tex, source/Makefile.am, source/dynamic/dynamic.cpp, source/libnormaliz/automorph.cpp, source/libnormaliz/automorph.h, source/libnormaliz/cone.cpp, source/libnormaliz/cone.h, source/libnormaliz/descent.cpp, source/libnormaliz/descent.h, source/libnormaliz/dynamic_bitset.h, source/libnormaliz/full_cone.cpp, source/libnormaliz/full_cone.h, source/libnormaliz/matrix.cpp, source/libnormaliz/matrix.h, source/libnormaliz/nmz_integral.cpp, source/libnormaliz/nmz_integrate.h, source/libnormaliz/nmz_nauty.cpp, source/libnormaliz/nmz_polynomial.cpp, source/libnormaliz/project_and_lift.cpp, source/libnormaliz/project_and_lift.h, source/libnormaliz/simplex.h, source/libnormaliz/vector_operations.cpp, source/libnormaliz/vector_operations.h
The first commit in this PR adds a new header file `source/libnormaliz/dynamic_bitset.h` which currently essentially contains this:
```C++
#include <boost/dynamic_bitset.hpp>
namespace libnormaliz {
typedef boost::dynamic_bitset<> dynamic_bitset;
}
```
The first commit also changes all the existing code to include the new header, instead of including the boost header directly.
The second commit then changes all the source code to use "our" `dynamic_bitset` instead of `boost::dynamic_bitset<>` (of course for now they are the same).
The ultimate motivation for this is that I would like to make it possible to compile Normaliz without Boost; right now, the dependency on Boost is the biggest issue I face in installing Normaliz on various systems. The biggest part of a patch achieving this goal …
=> Refactor boost::dynamic_bitset<> use

source/Makefile.am
Also remove libnormaliz/nmz_nauty.cpp and libnormaliz/output.cpp from
noinst_HEADERS as they are are already listed under libnormaliz_la_SOURCES
=> source/Makefile.am: reformat file lists for clarity

source/libnormaliz/cone_property.h
While technically, ClassGroup is implemented as std::vector<Integer>, it is
not a "true vector". Thus getVectorConeProperty() does not support it.
This change ensures that output_type(ClassGroup) returns OutputType::Complex
instead of OutputType::Vector, so that code using the generic property access
APIs does not end up trying to call getVectorConeProperty(ClassGroup).
This is an alternative to PR #242. While I still think that PR is superior, I need this situation to be resolved one way or another, so this PR is better than nothing for me.
Resolves #242.
=> Treat ClassGroup as a complex structure, not a vector

configure.ac
e-antic's C++ interface only depends on GMP(xx) and FLINT. (and arb through renf_elem.h)
see https://github.com/conda-forge/normaliz-feedstock/issues/10.
=> Don't overlink

.gitignore, doc/Normaliz.tex, install_normaliz.sh, install_pynormaliz.sh, source/libnormaliz/cone.cpp, source/libnormaliz/full_cone.cpp, source/libnormaliz/nmz_integral.cpp, source/libnormaliz/nmz_integrate.h, source/libnormaliz/nmz_polynomial.cpp, source/n64monitor.sh
Also remove some dead code
In normaliz.tex, there is still a reference to nmzIntegrate on Windows which says, among other things, that "NmzIntegrate can still be used (in all operating systems)", which I think is at best misleading? But I don't know what really is the state of things on Windows, so I didn't touch that paragraph.
=> Remove references to Qnormaliz, nmzIntegrate; fix typos

install_normaliz_with_eantic.sh, install_normaliz_with_opt.sh, install_scripts_opt/install_nmz_arb.sh, install_scripts_opt/install_nmz_cocoa.sh, install_scripts_opt/install_nmz_e-antic.sh, install_scripts_opt/install_nmz_e-antic_github.sh, install_scripts_opt/install_nmz_flint.sh, install_scripts_opt/install_nmz_flint_devel.sh, install_scripts_opt/install_nmz_nauty.sh
- don't force static linking GMP and CoCoA
- fix GMP_INSTALLDIR for e-antic
- don't override {C,CPP,LD}FLAGS provided by the user
With this, I can actually use these scripts on my computer :-)
=> Better GMP_INSTALLDIR, CFLAGS, CPPFLAGS, LDFLAGS handling

.travis.yml
- remove autotools-enfnormaliz-nauty build on Linux with clang:
we already test this config on macOS with clang
- remove macOS tests with xcode8.3 and xcode9.2: they add little benefit
(if Normaliz compiles with xcode7.3 and xcode10.2 then most likely with
these intermediate Xcode versions, too), but they cost us severely in CI
runtime, as we only can run 1-2 macOS jobs in parallel on Travis
- drop the `-makedistcheck` from the xcode7.3 build: it had no effect
=> Reduce number of Travis builds for faster CI turnaround times

.codecov.yml
This fixes a validation error reported by `yamllint`. Perhaps this will make the config actually work...
=> Fix .codecov.yml syntax

.codecov.yml
After years of useless documentation, Codecov finally started to improve in
that area. We now try to improve our .codecov.yml file based on these:
- <https://docs.codecov.io/docs/commit-status>
- <https://docs.codecov.io/docs/codecovyml-reference>
Please don't merge this immediately. I'd like to experiment with a few settings first.
=> Tweak Codecov settings

.github/workflows/ci-sage-linux.yml
This adds a GitHub Actions workflow, testing Normaliz with the new Sage portability testsuite (​see https://doc.sagemath.org/html/en/developer/portability_testing.html, ​​https://researchseminars.org/talk/SageDays109/7/)
On every push of a tag and on every pull request, this creates a "make dist" of Normaliz and then builds a portion of the Sage distribution (the current beta version), including Normaliz and PyNormaliz (from the Normaliz distribution just built) on a large number of different Linux distributions / configurations.
=> .github/workflows: Add Sage CI workflows

configure.ac
to support install on Debian.
Preview of a fixed build on debian-buster: https://github.com/mkoeppe/Normaliz/runs/797953312
=> configure.ac: Check for both -larb and -lflint-arb 

configure.ac
Experiment to see what happens if we drop these.
UPDATE: No ill effects visible on Travis, it also seems to work for me locally... so perhaps this could be merged, although there is some risk of regression (but a regression report would still be useful as it might give a clue as to what was meant to be achieved by having these rpath options in there in the first place)
=> configure.ac: drop hardcoded -rpath usage

source/libnormaliz/HilbertSeries.cpp, source/libnormaliz/cone.cpp, source/libnormaliz/full_cone.cpp, source/libnormaliz/simplex.cpp
This is a patch due to Benjamin Burton. To quote him:
This fixes several compile errors in the GMPXX-related code on systems where
size_t != unsigned long. This happens in particular on 64-bit windows. (You
might not be seeing this because you use MPIR on windows, but regina uses GMP
everywhere so probably I am building this code on additional platforms where
you are not.)
The compile error is related to overloaded functions in GMP that C++ cannot
choose between. I believe the problem is that you are passing size_t arguments
to GMP functions, but these GMP functions do not take size_t arguments. On
normal platforms this is not a problem since size_t == unsigned long, and GMP
functions *do* take unsigned long arguments. However, if size_t != unsigned
long then the compiler needs to cast …
=> Fix issues when size_t != unsigned long

source/libnormaliz/full_cone.cpp, source/libnormaliz/full_cone.h, source/libnormaliz/matrix.cpp
Sampling a run of A553_scale_2, I found several things that I could improve. Most importantly, I found that there are lots of calls `a*=b` where one of the operands is zero and calls `a-=b` where the right hand side is zero.
We are going to make such calls much faster in e-antic itself but it is beneficial to not perform any arithmetic in such cases. Note that the previous version of e-antic used a faster path of arithmetic here because it immediately identified such operands as `fmpq` rationals.
For me this brings down the runtime of A553_scale_2 from
```
real    27m7.131s
user    211m21.847s
sys     0m12.758s
```
to
```
real    15m10.432s
user    116m12.130s
sys     0m9.882s
```
=> speed up A553_scale_2

.github/workflows/ci.yml, install_scripts_opt/install_nmz_e-antic.sh, source/libnormaliz/cone.cpp, source/libnormaliz/cone.h, source/libnormaliz/general.h, source/libnormaliz/input.cpp, source/libnormaliz/input.h, source/libnormaliz/integer.h, source/libnormaliz/normaliz_exception.h, source/libnormaliz/output.cpp, source/libnormaliz/output.h, source/normaliz.cpp
for performance reasons, we swapped out std::shared_ptr with
boost::intrusive_ptr in the latest (and it actually seems) final rc of
e-antic.
=> adapt to latest change in e-antic

.github/workflows/ci-sage.yml
This fixes the Sage CI. See https://github.com/mkoeppe/Normaliz/actions/runs/1814541676 for a test run 
This reveals a number of portability problems, coming from e-antic. See https://trac.sagemath.org/ticket/31588
=> .github/workflows/ci-sage.yml: Use target ticket #31588

.github/workflows/ci.yml
Using ccache should speed up CI quite a bit
=> CI: use ccache, possibly fix Codecov issues

source/libnormaliz/HilbertSeries.cpp, source/libnormaliz/automorph.cpp, source/libnormaliz/collection.cpp, source/libnormaliz/cone.cpp, source/libnormaliz/cone_dual_mode.cpp, source/libnormaliz/descent.cpp, source/libnormaliz/face_lattice.cpp, source/libnormaliz/full_cone.cpp, source/libnormaliz/general.cpp, source/libnormaliz/general.h, source/libnormaliz/list_and_map_operations.h, source/libnormaliz/matrix.cpp, source/libnormaliz/matrix.h, source/libnormaliz/output.cpp, source/libnormaliz/project_and_lift.cpp, source/libnormaliz/signed_dec.cpp, source/libnormaliz/simplex.cpp, source/libnormaliz/sublattice_representation.cpp, source/libnormaliz/vector_operations.h
Hi! I'm on a long-term mission to reduce the number of compiler warnings on macOS (Xcode/clang) when building regina, so that important messages do not get lost in the noise. At the moment there are hundreds of warnings coming from normaliz, and so I've gone through and audited the normaliz code to quieten things down.
The vast majority of these warnings come from implicitly casting a larger integer type to a smaller type (and the majority of *these* come from implicitly casting size_t to a key_t). In most of these cases I've added a static_cast, which has two effects: the warnings are silenced, but also this is easily searchable if you ever plan to go through and make your use of integer types more consistent across normaliz. (I'm currently doing the same with regina, but it's a slow and …
=> Compiler warnings and loss of precision in integer assignments

source/libnormaliz/general.cpp, source/libnormaliz/version.h.in
An inline version of getVersion() is next to useless, one can simply
access NMZ_RELEASE directly.
A non-inline version however can be used to compare the runtime version
of libnormaliz to the compile time version. That can be beneficial to
catch certain kinds of bugs.
=> Don't inline getVersion()

source/libnormaliz/general.cpp
Description: source typo
Correct spelling error as reported by lintian in some binaries;
meant to silence lintian and eventually to be submitted to the
upstream maintainer.
Comment: spelling-error-in-binary
Author: Jerome Benoit <calculus_AT_rezozer_DOT_net>
Last-Update: 2022-09-10
=> correct typo as reported by lintian

configure.ac, source/libnormaliz/HilbertSeries.cpp, source/libnormaliz/vector_operations.h
The various coefficient getting/setting functions that use GMP integers/rationals directly have been removed, and so we need to convert from GMP <-> FLINT separately.
Closes: #412
=> Add FLINT 3 support

source/libnormaliz/HilbertSeries.cpp, source/libnormaliz/general.cpp, source/libnormaliz/general.h
`fmpz.h` is needed for `fmpz_init` on flint 3.
`timeval` from `sys/time.h` should be available for the forward declaration of `StartTime`.
I got this error when building for musl in Yggdrasil:
```
libnormaliz/general.cpp:168:16: error: aggregate ‘libnormaliz::timeval libnormaliz::TIME_global_begin’ has incomplete type and cannot be defined
struct timeval TIME_global_begin, TIME_step_begin;
^~~~~~~~~~~~~~~~~
libnormaliz/general.cpp:168:35: error: aggregate ‘libnormaliz::timeval libnormaliz::TIME_step_begin’ has incomplete type and cannot be defined
struct timeval TIME_global_begin, TIME_step_begin;
^~~~~~~~~~~~~~~
libnormaliz/general.cpp: In function ‘void libnormaliz::StartTime(libnormaliz::timeval&)’:
libnormaliz/general.cpp:174:36: error: cannot convert ‘libnormaliz::timeval*’ to …
```
=> two include fixes: timeval + fmpz

.github/workflows/ci.yml, install_scripts_opt/common.sh
It seems GitHub recently changed which packages they install by default in their macOS runners.
This may need some further tweaks, so please let's wait till it completes before merging, to make sure it is ready (if not I'll adjust it further)
=> Fix macOS CI by installing more dependencies explicitl

install_scripts_opt/install_nmz_flint.sh
It seems the FLINT download url has changed, with a "/download" now added to the address. Noticed when I was trying to compile a fresh version today.
=> adjust FLINT download url
